services:
  - type: web
    name: university-portal
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn university_portal.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: university_portal
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DJANGO_SETTINGS_MODULE
        value: "university_portal.settings"
      - key: ALLOWED_HOSTS
        value: "university-portal.onrender.com localhost 127.0.0.1"
    healthCheckPath: "/"
    plan: free
    autoDeploy: yes

databases:
  - name: university_portal
    plan: free