services:
  - type: web
    name: university-portal
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn university_portal.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: university-portal-db  # Changed to match the database name below
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: PYTHON_VERSION
        value: "3.11.9"
    plan: free

databases:
  - name: university-portal-db  # This creates the database first
    plan: free
    postgresVersion: "16"